version: "3"
services:
  app:
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MINIO_HOST: "minio:9000"
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    depends_on:
      - minio
  minio:
    container_name: minio_container
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./data:/data
#      - ./models:/models
    command: server /app
