# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13model_service.proto\x12\x11your_package_name\"q\n\x11TrainModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nparameter1\x18\x02 \x01(\x02\x12\x12\n\nparameter2\x18\x03 \x01(\x02\x12\x10\n\x08\x66\x65\x61tures\x18\x04 \x03(\x02\x12\x0e\n\x06labels\x18\x05 \x03(\x02\"8\n\x12TrainModelResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2i\n\x0cModelService\x12Y\n\nTrainModel\x12$.your_package_name.TrainModelRequest\x1a%.your_package_name.TrainModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_TRAINMODELREQUEST']._serialized_start = 42
    _globals['_TRAINMODELREQUEST']._serialized_end = 155
    _globals['_TRAINMODELRESPONSE']._serialized_start = 157
    _globals['_TRAINMODELRESPONSE']._serialized_end = 213
    _globals['_MODELSERVICE']._serialized_start = 215
    _globals['_MODELSERVICE']._serialized_end = 320
# @@protoc_insertion_point(module_scope)
